blank_issues_enabled: false
contact_links:
  - name: Support question?
    url: https://github.com/ericsizemore/numverify-api-client-php/discussions/categories/q-a
    about: If you have any questions about configuring or using Numverify, please open a new Q&A discussion.
